name = "armageddon-chess"
main = "worker.js"
compatibility_date = "2026-01-06"

[durable_objects]
bindings = [
  { name = "GAME_ROOMS", class_name = "GameRoom" }
]

[[migrations]] 
tag = "v1" 
new_sqlite_classes = ["GameRoom"]
