name = "armageddon-chess"
main = "worker.js"
compatibility_date = "2026-01-07"

[durable_objects]
bindings = [
  { name = "GAME_ROOMS", class_name = "GameRoom" }
]

[[durable_objects.bindings]]
name = "ROOM_INDEX"
class_name = "RoomIndex"

[sqlite]
enabled = true

[[migrations]]
tag = "v1"
new_sqlite_classes = ["GameRoom"]